name: Project Test Workflow
on:
  # Schedule updates (each hour)
  #  schedule: [{cron: "0 */6 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["development","docker-build"] }
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install
      - name: Test all projects
        run: pnpm test
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y
      - name: Set up Docker Buildx
        run: |
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx
          docker buildx create --use
      - name: Build Docker image
        run: docker build -t your-image-name:latest .